public class BiodataHernanda {
    public static void main(String[] args) {
        System.out.printIn(x:"Nama          : Hernanda Rizka Utami");
        System.out.printIn(x:"TTL           : Sidoarjo, 01 Maret 2004");
        System.out.printIn(x:"Alamat        : Betas, Kepulungan,, Gempol");
        System.out.printIn(x:"Jenis Kelamin : Perempuan");
        System.out.printIn(x:"Agama         : Islam");
        System.out.printIn(x:"Email         : hernandar0606@gmail.com");
        System.out.printIn(x:"Kuliah        : Politeknik Pegeri Malang");
        System.out.printIn(x:"Program Studi : Sistem Informasi Bisnis");
        System.out.printIn(x:"Hobi          : Tidur");
        System.out.printIn(x:"BB/TB         : 48/158");
    }
}